name: Build Electron App
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    name: Build for ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [ ubuntu-latest, windows-latest, ubuntu-24.04-arm, macos-latest, macos-15-intel ]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: write
      contents: read
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
      - name: Setup macOS signing
        if: ${{ startsWith(matrix.os, 'macos-') }}
        uses: apple-actions/import-codesign-certs@v6
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_FILE_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      - name: Install system dependencies
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          sudo apt update
          sudo apt install rpm squashfs-tools
          # sudo apt install -y \
          #   flatpak \
          #   flatpak-builder \
          #   elfutils
          # flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo 
          # flatpak install --user -y flathub \
          #   org.freedesktop.Platform//25.08 \
          #   org.freedesktop.Sdk//25.08 \
          #   org.electronjs.Electron2.BaseApp//25.08
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install node dependencies
        run: npm i --verbose || npm i --verbose || npm i --verbose
      - name: Make distributables
        run: npm run make --verbose
        env:
          APPLE_ID_EMAIL: ${{ secrets.APPLE_ID_EMAIL }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build-artifacts-${{ matrix.os }}-${{ github.run_id }}
          path: out/make/**   
  release:
    name: Release as draft
    permissions:
      contents: write
    needs: [ build ]
    runs-on: ubuntu-latest
    steps: 
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: dist
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.5.0
        with:
          overwrite_files: false
          files: |
            dist/**/**
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
